In [38]:
import pandas as pd
import matplotlib as plt

In [39]:
df_country = pd.read_html("https://www.worldometers.info/co2-emissions/co2-emissions-by-country/")
len(df_country)

1

In [40]:
df_country = pd.read_html("https://www.worldometers.info/co2-emissions/co2-emissions-by-country/", index_col=0)[0]
df_country

,Country,"CO2 Emissions (tons, 2022)",1 Year Change,Population (2022),Per capita,Share of world
#,,,,,,
1,China,12667428430,-0.39%,1425179569,8.89,32.88%
2,United States,4853780240,1.78%,341534046,14.21,12.60%
3,India,2693034100,6.52%,1425423212,1.89,6.99%
4,Russia,1909039310,-1.22%,145579899,13.11,4.96%
5,Japan,1082645430,0.65%,124997578,8.66,2.81%
...,...,...,...,...,...,...
202,Saint Pierre & Miquelon,37110,-1.46%,5732,6.47,0.00%
203,Anguilla,22810,3.63%,14180,1.61,0.00%
204,Falkland Islands,21770,0.14%,3490,6.24,0.00%
205,Saint Helena,17900,12.30%,5343,3.35,0.00%
206,Faeroe Islands,2110,0.48%,54011,0.04,0.00%

In [41]:
df_country.info()

<class 'pandas.core.frame.DataFrame'>
Index: 206 entries, 1 to 206
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Country                      206 non-null    object
 1   CO2 Emissions  (tons, 2022)  206 non-null    int64
 2   1 Year  Change               206 non-null    object
 3   Population  (2022)           206 non-null    int64
 4   Per  capita                  206 non-null    float64
 5   Share  of world              206 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 11.3+ KB

In [42]:
df_country = df_country.rename({"Share  of world": "World percentage"}, axis="columns")

,Country,"CO2 Emissions (tons, 2022)",1 Year Change,Population (2022),Per capita,World percentage
#,,,,,,
1,China,12667428430,-0.39%,1425179569,8.89,32.88%
2,United States,4853780240,1.78%,341534046,14.21,12.60%
3,India,2693034100,6.52%,1425423212,1.89,6.99%
4,Russia,1909039310,-1.22%,145579899,13.11,4.96%
5,Japan,1082645430,0.65%,124997578,8.66,2.81%
...,...,...,...,...,...,...
202,Saint Pierre & Miquelon,37110,-1.46%,5732,6.47,0.00%
203,Anguilla,22810,3.63%,14180,1.61,0.00%
204,Falkland Islands,21770,0.14%,3490,6.24,0.00%
205,Saint Helena,17900,12.30%,5343,3.35,0.00%
206,Faeroe Islands,2110,0.48%,54011,0.04,0.00%

In [43]:
df_country["World percentage"].str.rstrip("%").astype(float)

KeyError: 'World percentage'